services:
   catalogdb:
        image: postgres    

   basketdb:
         image: postgres 

   distributedCache:
        image: redis

   orderdb:
        image: mcr.microsoft.com/mssql/server

   messageBroker:
        image: rabbitmq:management
        

   catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: ServiceCatalog/Catalog.API/Dockerfile
   basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
          context: .
          dockerfile: Basket/Basket.API/Dockerfile
   discount.grpc:
    image: ${DOCKER_REGISTRY-}discountgrpc
    build:
      context: .
      dockerfile: Services/Discount/Discount.Grpc/Dockerfile

   ordering.api:
    image: ${DOCKER_REGISTRY-}orderingapi
    build:
      context: .
      dockerfile: Services/Ordering/Ordering.API/Dockerfile

   yarpapigateway:
    image: ${DOCKER_REGISTRY-}yarpapigateway
    build:
      context: .
      dockerfile: ApiGateways/YarpApiGateway/Dockerfile

volumes: 
    postgres_catalog:   
    postgres_basket:



