services:
   catalogdb:
        image: postgres    

  catalog.api:
    image: ${DOCKER_REGISTRY-}catalogapi
    build:
      context: .
      dockerfile: ServiceCatalog/Catalog.API/Dockerfile

volumes: 
    postgres_catalog:    
