services:
 catalogdb:
    container_name: catalogdb
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=postgres
        - POSTGRES_DB=Catalogdb
    restart: always
    ports:
        - "5432:5432"
    volumes:
        - postgres_catalog:/var/lib/postgressql/data/       
 catalog.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
      - ConnectionStrings__Database=Server=localhost;Port=5432;Database=Catalogdb;User Id=postgres;Password=postgres;Include Error Detail=true  
    depends_on:
       - catalogdb
    ports:
      - "6060:8080"
      - "6061:8081"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
