services:
   catalogdb:
        image: postgres    

   basketdb:
         image: postgres 

   distributedCache:
        image: redis

   catalog.api:
        image: ${DOCKER_REGISTRY-}catalogapi
        build:
            context: .
            dockerfile: ServiceCatalog/Catalog.API/Dockerfile
   basket.api:
        image: ${DOCKER_REGISTRY-}basketapi
        build:
          context: .
          dockerfile: Basket/Basket.API/Dockerfile

volumes: 
    postgres_catalog:   
    postgres_basket:

